#!/bin/bash
set +x

BASEDIR=`cd "$(dirname "$0")"; pwd`
ARTIFACT_ID=`basename "$BASEDIR"`

WILDFLY_HOME=${WILDFLY_HOME:-$PWD/wildfly-8.2.0.Final}
export WILDFLY_HOSTNAME=${WILDFLY_HOSTNAME:-localhost}
WILDFLY_PORT_OFFSET=${WILDFLY_PORT_OFFSET:-0}
export WILDFLY_PORT=${WILDFLY_PORT:-$((9990+WILDFLY_PORT_OFFSET))}
export WILDFLY_USERNAME=${WILDFLY_USERNAME:-fulano}
export WILDFLY_PASSWORD=${WILDFLY_PASSWORD:-senha}

export JBOSS_HOME=$WILDFLY_HOME

case $1 in
    generate)
        cd "$BASEDIR"
        mvn archetype:generate -DgroupId=com.example -DartifactId=$ARTIFACT_ID -DarchetypeArtifactId=maven-archetype-webapp -DinteractiveMode=false
        rsync -a $ARTIFACT_ID/ .
        rm -rf $ARTIFACT_ID/ src/main/webapp/WEB-INF/web.xml
        for f in `find . -type f -name \*.patch`
        do
            f=${f%%.patch}
            [ -f $f ] || continue
            cp $f $f.original
            patch $f $f.patch
        done
        mvn eclipse:eclipse
    ;;
    package)
        mvn package
    ;;
    test)
        java -cp "$WILDFLY_HOME"/bin/client/jboss-cli-client.jar:target/classes: com.example.Main $WILDFLY_HOSTNAME $WILDFLY_PORT $WILDFLY_USERNAME $WILDFLY_PASSWORD
    ;;
    add-user)
        "$WILDFLY_HOME"/bin/add-user.sh -s -u $WILDFLY_USERNAME -p $WILDFLY_PASSWORD
    ;;
    start)
        "$WILDFLY_HOME"/bin/standalone.sh -b $WILDFLY_HOSTNAME -Djboss.socket.binding.port-offset=$WILDFLY_PORT_OFFSET -bmanagement=$WILDFLY_HOSTNAME &
    ;;
    stop)
        "$WILDFLY_HOME"/bin/jboss-cli.sh --controller=$WILDFLY_HOSTNAME:$WILDFLY_PORT -c :shutdown
    ;;
    deploy)
        mvn wildfly:deploy
    ;;
    undeploy)
        mvn wildfly:undeploy
    ;;
    clean)
        mvn clean
        find . -type f ! \( \
            -path './.git/*' -o -name .gitignore -o \
            -name README.md -o \
            -name run -o \
            -name Main.java -o \
            -name \*.patch -o \
            -path './wildfly-8.2.0.Final/*' -o -name wildfly-8.2.0.Final\* \
        \) -delete
        find . -type d -empty -delete
        ;;
    *)
        echo "Comando inválido: $1"
esac
